### ISSUE TITLE
Consider adding Deref and From traits for noisy float types

### ISSUE THREAD

**Issue by jerry73204** [SergiusIW/noisy_float-rs#29]
It enables the convenient API like this. 

```rust
/* library */

fn rotation_range(lo: impl Into<R64>, up: impl Into<R64>) -> R64 {
    // checked conversions, panic on non-finite values
    let lo = lo.into();
    let up = up.into();

    // with Deref, we can call f64::to_radians without explicit unpacking
    let degrees: R64 = up - lo;
    let radians_raw: f64 = degrees.to_radians();

    // checked conversion
    let radians: R64 = radians_raw.into();

    // with Deref, we can write *x instead of x.raw()
    dbg!("{:.3}", *radians);

    radians
}

/* user */

fn main() {
    // user writes this instead of R64::new(1.2)
    let radians = rotation_range(30.0, 60.0);
}
```

**Comment by SergiusIW** [comment]
While I would appreciate less verbose ways of working with `NoisyFloat` types, I think these implementations may be an abuse of the traits.

E.g. `impl From<f64> for R64` may panic when `from` is called with `NaN` in debug mode. However, the `From` [documentation](https://doc.rust-lang.org/std/convert/trait.From.html) specifies that "this trait must not fail."

Also, the `Deref` [documentation](https://doc.rust-lang.org/std/ops/trait.Deref.html) specifies "Deref should only be implemented for smart pointers to avoid confusion".

That being said, I think you can simplify some of your examples. `degrees.to_raidans()` can be invoked and returns an R64 if the `num_traits::float::Float` trait is imported (e.g. if you `use noisy_float::prelude::*;`). Also, you can use the convenience method `r64(1.2)` instead of writing out `R64::new(1.2)`.
